# Generated by Django 4.2.9 on 2024-01-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer_code', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('port_architecture', models.CharField(max_length=100)),
                ('manageable', models.BooleanField()),
                ('bus_speed', models.CharField(max_length=100)),
                ('throughput', models.CharField(max_length=100)),
                ('total_ports', models.IntegerField()),
                ('sfp_ports', models.IntegerField()),
                ('poe_ports', models.CharField(max_length=100)),
                ('enclosure_type', models.CharField(max_length=100)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('depth_mm', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceProposal',
        ),
        migrations.DeleteModel(
            name='Switch',
        ),
    ]
