# Generated by Django 4.2.9 on 2024-01-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_switches_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('supported_networks', models.CharField(max_length=100)),
                ('wifi_standard', models.CharField(max_length=100)),
                ('mesh_system', models.BooleanField(default=False)),
                ('vpn_support', models.BooleanField(default=False)),
                ('qos', models.BooleanField(default=False, verbose_name='QoS (Traffic Control)')),
                ('print_server', models.BooleanField(default=False)),
                ('encryption_standard', models.CharField(max_length=100)),
                ('wan_ports', models.PositiveIntegerField()),
                ('lan_ports_number', models.PositiveIntegerField()),
                ('sim_socket', models.BooleanField(default=False)),
                ('antennas', models.PositiveIntegerField()),
                ('transmission_speed_24ghz', models.PositiveIntegerField(verbose_name='Transmission Speed 2.4GHz')),
                ('transmission_speed_5ghz', models.PositiveIntegerField(verbose_name='Transmission Speed 5GHz')),
                ('width_mm', models.PositiveIntegerField(verbose_name='Width [mm]')),
                ('height_mm', models.PositiveIntegerField(verbose_name='Height [mm]')),
                ('depth_mm', models.PositiveIntegerField(verbose_name='Depth [mm]')),
                ('image', models.ImageField(default='routers_images/default_no_image.png', upload_to='routers_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Router',
        ),
    ]
