# Generated by Django 4.2.9 on 2024-01-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_routers_delete_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='routers',
            name='manufacturer_code',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='routers',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
