# Generated by Django 4.2.9 on 2024-01-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_routers_manufacturer_code_alter_routers_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routers',
            name='manufacturer_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routers',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
