# Generated by Django 4.2.9 on 2024-01-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_alter_routers_manufacturer_code_alter_routers_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturer_code', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('maximum_print_format', models.CharField(max_length=100)),
                ('print_resolution_black', models.CharField(max_length=100)),
                ('print_resolution_color', models.CharField(max_length=100)),
                ('print_speed_black', models.PositiveIntegerField()),
                ('print_speed_color', models.PositiveIntegerField()),
                ('duty_cycle', models.PositiveIntegerField()),
                ('automatic_duplex_printing', models.BooleanField(default=False)),
                ('output_tray_capacity', models.PositiveIntegerField()),
                ('input_tray_capacity', models.PositiveIntegerField()),
                ('display', models.CharField(max_length=100)),
                ('memory', models.PositiveIntegerField()),
                ('wired_network_support', models.BooleanField(default=False)),
                ('interface', models.CharField(max_length=100)),
                ('wifi', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('depth_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.CharField(max_length=100)),
                ('image', models.ImageField(default='printers_images/default_no_image.png', upload_to='printers_images/')),
            ],
        ),
    ]
