# Generated by Django 4.2.9 on 2024-01-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_ethernetsocket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethernetsocket',
            name='manufacturer_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
