# Generated by Django 4.2.9 on 2024-01-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_gameconsole'),
    ]

    operations = [
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturer_code', models.CharField(max_length=100)),
                ('frame_color', models.CharField(max_length=100)),
                ('matrix_type', models.CharField(max_length=100)),
                ('screen_size_inches', models.DecimalField(decimal_places=2, max_digits=5)),
                ('screen_size_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hd_format', models.CharField(max_length=100)),
                ('resolution', models.CharField(max_length=100)),
                ('refresh_rate', models.PositiveIntegerField()),
                ('tuner', models.CharField(max_length=100)),
                ('hdr_technology', models.CharField(max_length=100)),
                ('game_mode', models.BooleanField(default=False)),
                ('backlight_type', models.CharField(max_length=100)),
                ('smart_tv', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('hdmi', models.PositiveIntegerField()),
                ('hbbtv', models.BooleanField(default=False)),
                ('arc', models.BooleanField(default=False)),
                ('ambilight', models.BooleanField(default=False)),
                ('dolby_technologies', models.CharField(max_length=100)),
                ('total_speaker_power', models.PositiveIntegerField()),
                ('number_of_speakers', models.PositiveIntegerField()),
                ('number_of_hdmi_ports', models.PositiveIntegerField()),
                ('scart_connector', models.BooleanField(default=False)),
                ('ethernet_port', models.BooleanField(default=False)),
                ('ci_slot', models.BooleanField(default=False)),
                ('new_energy_class', models.CharField(max_length=100)),
                ('height_with_stand', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width_with_stand', models.DecimalField(decimal_places=2, max_digits=6)),
                ('depth_with_stand', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(default='tv_images/default_no_image.png', upload_to='tv_images/')),
            ],
        ),
    ]
