# Generated by Django 4.2.9 on 2024-01-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_desk_officesupplies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Manufacturer')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('length', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('shielding', models.CharField(max_length=100, verbose_name='Shielding')),
                ('cores', models.CharField(max_length=100, verbose_name='Cores')),
                ('insulation', models.CharField(max_length=100, verbose_name='Insulation')),
                ('packaging_dimensions', models.CharField(max_length=100, verbose_name='Packaging Dimensions (WxDxH cm)')),
            ],
        ),
    ]
