# Generated by Django 4.2.9 on 2024-01-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_alter_desk_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconsole',
            name='clock_speed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gameconsole',
            name='ram_memory',
            field=models.CharField(max_length=100),
        ),
    ]
