# Generated by Django 4.2.9 on 2024-02-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_alter_gameconsole_clock_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='depth_cm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printer',
            name='duty_cycle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printer',
            name='height_cm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printer',
            name='input_tray_capacity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printer',
            name='memory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printer',
            name='output_tray_capacity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printer',
            name='print_speed_black',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printer',
            name='print_speed_color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printer',
            name='weight_kg',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printer',
            name='width_cm',
            field=models.CharField(max_length=100),
        ),
    ]
