# Generated by Django 4.2.9 on 2024-02-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_alter_printer_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routers',
            name='transmission_speed_24ghz',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routers',
            name='transmission_speed_5ghz',
            field=models.CharField(max_length=100),
        ),
    ]
