# Generated by Django 4.2.9 on 2024-02-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_alter_tv_smart_tv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='total_speaker_power',
            field=models.CharField(max_length=100),
        ),
    ]
