# Generated by Django 4.2.9 on 2024-02-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0025_alter_tv_total_speaker_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv',
            name='hdmi',
        ),
    ]
