# Generated by Django 4.2.9 on 2024-02-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0027_remove_tv_total_speaker_power_tv_hdmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='total_speaker_power',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tv',
            name='refresh_rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tv',
            name='smart_tv',
            field=models.BooleanField(default=False),
        ),
    ]
