# Generated by Django 4.2.9 on 2024-02-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0029_remove_tv_hdmi_alter_tv_total_speaker_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='hdmi',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
